### ISSUE TITLE
constant not working properly

### ISSUE THREAD

**Issue by Freyert** [folktale/core.lambda#5]
Constant wasn't working properly from what I could tell. Looked like the Curry was messed up.

```
var cat = lambda.constant('cat');
cat(); //=> [Function]
```

Had to resort to:

```
var cat = lambda.identity.bind(lambda, 'cat');
cat(); // 'cat'
```

Also tried `var cat = arity.binary(lambda.constant)('cat')`, but if I call it without arguments it returns `[Function]` as well.

**Comment by robotlolita** [comment]
@Freyert constant necessarily takes two arguments. The way `curry` works `core.lambda` requires you to pass the right number of arguments to the function, so it's similar to how it works in Lambda Calculus (and languages based on it, like Haskell).

In particular, this means that `constant` is a function with the following type:

``` haskell
constant :: forall a. forall b. a -> b -> a
```

So, if you follow the usage from the types, it's easy to see the relationship:

``` haskell
1 :: Int
constant 1 :: forall b. b -> Int
(constant 1) 2 :: Int
((constant 1) 2) 3 :: TypeError: can't apply Int to Int
```

The `curry` function tries to preserve that relationship, so:

``` js
constant() // :: forall a. forall b. a -> b -> a
constant(1) // :: forall b. b -> Int
constant(1, 2), constant(1)(2) // :: Int
constant(1, 2, 3), constant(1)(2)(3), constant(1, 2)(3), constant(1)(2, 3) 
// :: TypeError: can't apply Int to Int
```

When you don't pass it any argument (not possible in the Lamba Calculus), there are two ways to approach it. You either throw an error telling the user that the function has to take at least one argument, or you return the original function. Both options are, imho, pretty meh, but the `curry` chooses the latter.

**Comment by robotlolita** [comment]
Closing as `wontfix` for the reasons above.

**Comment by Freyert** [comment]
@robotlolita Wow, that was an incredible explanation. Thanks! I learned a bunch, any recommended reading for the curious?
